### ISSUE TITLE
AttributeError: module 'torch.distributed.checkpoint' has no attribute 'FsspecWriter'

### ISSUE THREAD

**Issue by gaseln** [PrimeIntellect-ai/OpenDiloco#35]
Hello,

I encountered the following error while running the code:

```
AttributeError: module 'torch.distributed.checkpoint' has no attribute 'FsspecWriter'
```

The error points to line 74 in `open_diloco/ckpt_utils.py`. I suspect this issue may be related to the recent reversion of a commit that had moved `dcp.fsspec.FsspecWriter` to the PyTorch public API (see [PyTorch PR #121508](https://github.com/pytorch/pytorch/pull/121508)).

As a current workaround, I moved [`_fsspec_filesystem.py`](https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/_fsspec_filesystem.py) into the `open_diloco` folder and replaced the `dcp.FsspecWriter` and `dcp.FsspecReader` in `ckpt_utils.py` with functions from `_fsspec_filesystem.py`. 

If this approach is suitable, I’d be happy to submit a pull request with my local changes for your review.

Best regards,
Elnur

**Comment by Jackmin801** [comment]
Hi Elnur,

Thanks for bringing this to our attention! Yea it seems like pytorch dcp team decided to take fsspec private. Maybe @fegin or @wz337 know more about why?

---
Moving the content of `_fsspec_filesystem.py` into this repo seems a bit janky though.

Theres a few other ways to fix it
1. Import `FsspecWriter` from it's new path
```python
from torch.distributed.checkpoint._fsspec_filesystem import FsspecWriter
```
2. Pin the torch version to before the PR you mentioned

Personally I prefer 2 as it solves this problem and any future backwards compatibility issues. @samsja might have a different opinion on this though.

**Comment by gaseln** [comment]
@Jackmin801, thank you for highlighting these straightforward solutions: they are indeed much simpler to implement.

@samsja, great! I'll check it out!
