### ISSUE TITLE
Discrepancy in replicating Figure 3 baseline experiment with 4 GPUs Instead of 8

### ISSUE THREAD

**Issue by gaseln** [PrimeIntellect-ai/OpenDiloco#36]
Hello!

I attempted to replicate the baseline experiment depicted as the orange line "Baseline: 8x batch size with data parallelism" in Figure 3 using the following launch code:

```bash
torchrun --nproc_per_node=4 \
    train_fsdp.py \
    --sharding-strategy NO_SHARD \
    --per-device-train-batch-size 32 \
    --precision bf16-mixed \
    --total-batch-size 512 \
    --total-steps 88000 \
    --project OpenDiLoCo \
    --lr 4e-4 \
    --path_model PrimeIntellect/llama-150m-fresh \
    --log-activations-steps 200 \
    --ckpt.interval 8000 \
    --ckpt.path 150_ckpt
```

This is compared to the launch code provided under the "150m DDP Baseline" section in the README:

```bash
torchrun --nproc_per_node=8 \
    train_fsdp.py \
    --sharding-strategy NO_SHARD \
    --per-device-train-batch-size 32 \
    --precision bf16-mixed \
    --total-batch-size 512 \
    --total-steps 88000 \
    --project OpenDiLoCo \
    --lr 4e-4 \
    --path_model PrimeIntellect/llama-150m-fresh \
    --log-activations-steps 200 \
    --ckpt.interval 8000 \
    --ckpt.path 150_ckpt
```

The only difference is the number of GPUs used for the experiment; unfortunately, I have only 4 GPUs at my disposal.

After examining the code in `train_fsdp.py`, it seems the executions should be very similar due to the same amount of computation corresponding to one step of the algorithm. Specifically, the code includes:

```python
assert config.total_batch_size % world_size == 0
batch_size = config.total_batch_size // world_size

assert batch_size % config.per_device_train_batch_size == 0
gradient_accumulation_steps = batch_size // config.per_device_train_batch_size

# ...

for step, batch in enumerate(train_dataloader, start=start_step * gradient_accumulation_steps):
    real_step = (step + 1) // gradient_accumulation_steps
    is_accumulating = bool((step + 1) % gradient_accumulation_steps)

    # ...

    with model.no_sync() if is_accumulating else nullcontext():
        outputs = model(**batch)
        loss = outputs.loss / gradient_accumulation_steps

        loss_batch += loss.detach()

        scaler.scale(loss).backward()
```

Given that `config.total_batch_size` is the same in both the paper's and my runs, the execution in my case ends up having twice the `gradient_accumulation_steps` due to having half the number of GPUs. This means that during one real step, the same number of batches are utilized. Therefore, aside from stochasticity in the AdamW optimizer, the runs should be approximately similar.

However, I was surprised to observe worse results, which I present in the plot below:

![Plot of Results](https://github.com/user-attachments/assets/6824dbd9-b53f-4e13-b2f2-a4756f126981)

Compared to Figure 3 in the [OpenDiLoCo paper](https://arxiv.org/pdf/2407.07852), the perplexity I obtained is about one point lower. While this might seem like a small difference, considering that the baseline experiment with a 1x batch size yields around 16 perplexity, achieving around 15 perplexity with an 8x larger batch size might undermine the efficacy of the entire approach.

What do you think could be causing this issue? Did I make a mistake in the launch code, or is there indeed a significant difference between running the code on 4 GPUs versus 8 GPUs?

**Comment by Jackmin801** [comment]
I think you are correct in your assumption that the change in `nproc-per-node` should not affect the experiment. That should be no issue.

As for the result of your experiment, I dont think anything is wrong, the perplexity graph you obtained is similar to the blue line in the paper:
![image](https://github.com/user-attachments/assets/16c45e46-928a-4a24-a46b-584de84c1c89)

The orange line is obtained from setting a batch size of `4096`.

The purpose of the plot is to show that using DiLoCo results in a graph that will be between DDP with the chosen per worker batch size (1/8 the flops of the DiLoCo with 8 workers) and DDP with 8 times the batch size (similar flops to DiLoCo with 8 workers). What we observe is that beyond ~86k steps, the perplexity is roughly the same, making the reduced communication overhead of using DiLoCo a "free lunch"

**Comment by gaseln** [comment]
Thank you for pointing out the need to adjust the batch size to replicate the orange line results. It would be helpful to include a comment about this in the README file to prevent misunderstandings.
